---
title: "bootstrap_CI_1.hseason"
output: pdf_document
date: "2026-01-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(readr)
library(dplyr)
library(lme4)
library(tidyr)
library(myFunctions) #custom bootstrap function
library(ggplot2)

#optimizer for glmer
cntrl <- glmerControl(optimizer = "bobyqa", tol = 1e-4, optCtrl=list(maxfun=100000))

```

```{r reading in data, results = 'hide', message = FALSE}
## dataset for part 1 of conditional model
ws_model_data <- read_csv(here("data", "clean", "commute_data.csv")) %>% 
  
  #restricting to only winter study months
  filter((paste(month, day, sep = "-") >= "11-15" &
            paste(month, day, sep = "-") <= "12-15") |
          (paste(month, day, sep = "-") >= "3-1" &
            paste(month, day, sep = "-") <= "3-30")) %>% 
  
  #removing days when there is less than 5 GPS point
  #unless the result is Jardine
  filter(!(n_point < 5 & terr_bin == F)) %>% 
  
  #only columns used in model
  dplyr::select(terr_bin, raven_id, rf_active_kill, final_take_bms1, final_take, 
                hunt_season, rf_avg_terr_kill_density, dist2nentrance, 
                study_period, temp_max, snow_depth, prop_group_left_terr) %>% 
  
  #making sure rows are complete
  filter(complete.cases(.)) 
  

## dataset for part 2 of conditional model
hunt_model_data <- read_csv(here("data", "clean", "commute_data.csv")) %>%

  #only have days ravens decided to leave territory
  filter(terr_bin == 1) %>% 
  
  #removing days when there is less than 5 GPS point
  #unless the result is Jardine
  filter(!(n_point < 5 & hunt_bin == F)) %>% 
  
  
  #only columns used in model
  dplyr::select(hunt_bin, raven_id, final_take_bms1, final_take, hunt_season,
                dist2nentrance, study_period, temp_max, snow_depth, prop_group_visit_hunt) %>% 
  
  #making sure rows are complete
  filter(complete.cases(.)) 
```
```{r (1) hunting season model}
mod_terr_hseason <- glmer(terr_bin ~ (1|raven_id) + rf_active_kill + hunt_season + scale(rf_avg_terr_kill_density) + 
                            scale(dist2nentrance) + study_period * scale(temp_max) + scale(snow_depth) + scale(prop_group_left_terr),
                         data = ws_model_data,
                         family = "binomial",
                         nAGQ = 40,
                         control = cntrl)
summary(mod_terr_hseason)
```
```{r (1) bootstrap (season), echo=FALSE, warning=FALSE}
#bootstrapping parameter values from model simulations
boot_param_CI(nsim = 20000, model = mod_terr_hseason, data = ws_model_data)[[3]]
```