---
title: "bootstrap_CI_2.biomass"
output: pdf_document
date: "2026-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(readr)
library(dplyr)
library(lme4)
library(tidyr)
library(myFunctions) #custom bootstrap function
library(ggplot2)

#optimizer for glmer
cntrl <- glmerControl(optimizer = "bobyqa", tol = 1e-4, optCtrl=list(maxfun=100000))

```
```{r reading in data, results = 'hide', message = FALSE}
## dataset for part 2 of conditional model
hunt_model_data <- read_csv(here("data", "clean", "commute_data.csv")) %>%

  #only have days ravens decided to leave territory
  filter(terr_bin == 1) %>% 
  
  #removing days when there is less than 5 GPS point
  #unless the result is Jardine
  filter(!(n_point < 5 & hunt_bin == F)) %>% 
  
  
  #only columns used in model
  dplyr::select(hunt_bin, raven_id, final_take_bms1, final_take, hunt_season,
                dist2nentrance, study_period, temp_max, snow_depth, prop_group_visit_hunt) %>% 
  
  #making sure rows are complete
  filter(complete.cases(.)) 
```
```{r (2) bms_window model}
mod_hunt_bms <- glmer(hunt_bin ~ (1|raven_id) + scale(final_take_bms1) + scale(dist2nentrance) + 
                         scale(prop_group_visit_hunt) + scale(temp_max) + scale(snow_depth),
                       data = hunt_model_data,
                       family = "binomial",
                       nAGQ = 40,
                       control = cntrl)
summary(mod_hunt_bms)
```
```{r (2) bootstrap (biomass), echo=FALSE, warning=FALSE}
#creating labels for covariate names in plot
cov_labs <- c("Distance", "Hunting Biomass", "Proportion Traveling",
              "Snow Depth", "Max Temp")

#bootstrapping parameter values from model simulations
boot_param_CI(nsim = 10000, model = mod_hunt_bms, data = hunt_model_data)[[3]] +
  scale_y_dsicrete(label = cov_labs) +
  labs(x = "Predicted Probaiblity")
```